src/lib/biokepi_pipeline.ml
src/lib/biokepi_run_environment.ml
src/lib/biokepi_target_library.ml

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/hammerlab/biokepi/5)

Add Virmid (target-lib, pipeline, and tool)

---

src/lib/biokepi_target_library.ml

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/hammerlab/biokepi/11)

add sorting and indexing of bams as dependency to strelka

---

src/lib/biokepi_target_library.ml

Closes #12
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/hammerlab/biokepi/13)

ensure working dir in strelka

---

src/lib/biokepi_target_library.ml

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/hammerlab/biokepi/14)

give threads argument to samtools sort

---

src/lib/biokepi_pipeline.ml
src/lib/biokepi_target_library.ml

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/hammerlab/biokepi/19)

Specify reference build for alignment

---

src/lib/biokepi_common_pipelines.ml
src/lib/biokepi_pipeline.ml
src/lib/biokepi_target_library.ml

Fixes #10
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/hammerlab/biokepi/20)

add bwa mem option

---

src/lib/biokepi_pipeline.ml
src/lib/biokepi_region.ml
src/lib/biokepi_somatic_targets.ml
src/lib/biokepi_util_targets.ml

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/hammerlab/biokepi/22)

Add haplotype caller from GATK

---

src/lib/biokepi_util_targets.ml

Side point on this - does it make sense to name `if_fails_activate` and `success_triggers` more similarly?
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/hammerlab/biokepi/31)

remove sam after creating bam

---

src/lib/biokepi_pipeline.ml
src/lib/biokepi_region.ml
src/lib/biokepi_run_environment.ml

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/hammerlab/biokepi/32)

Add hg18 reference

---

src/lib/biokepi_run_environment.ml
src/lib/biokepi_somatic_targets.ml
src/lib/biokepi_util_targets.ml

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/hammerlab/biokepi/39)

Add bedtools and bamtofastq

---

src/lib/biokepi_pipeline.ml
src/lib/biokepi_run_environment.ml
src/lib/biokepi_util_targets.ml

This adds “input bams” and the step “bam-to-fastq”.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/hammerlab/biokepi/42)

Bams in pipelines

---

src/lib/biokepi_run_environment.ml

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/hammerlab/biokepi/44)

Add strelka to default toolkit

---

src/lib/run_environment.ml

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/hammerlab/biokepi/53)

Fix hg18 dbSNP url

---

_oasis
src/lib/pipeline.ml
src/lib/reference_genome.ml
src/lib/reference_genome.mli
src/lib/run_environment.ml
src/lib/star.ml
src/lib/workflow_utilities.ml

- Adds a GTF transcript file for B37/38
- Add STAR aligner module with `index` and `align` functions
- Add STAR to the pipeline file as an alternative aligner
For this last piece, I'm interested to hear your thoughts @seb on splitting RNA/DNA pipelines
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/hammerlab/biokepi/55)

Add STAR RNA aligner

---

_oasis
src/lib/cufflinks.ml
src/lib/run_environment.ml
src/lib/star.ml
src/lib/stringtie.ml

- Also updates STAR aligner to recommend settings for cufflinks (outputting XS attribute in BAM file)
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/hammerlab/biokepi/58)

Add stringtie and cufflinks modules

---

src/lib/pipeline.ml

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/hammerlab/biokepi/59)

Remove single end todo

---

_oasis
src/lib/hisat.ml
src/lib/pipeline.ml
src/lib/run_environment.ml

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/hammerlab/biokepi/61)

Adding HISAT RNA aligner

---

src/lib/star.ml

Fixes #64
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/hammerlab/biokepi/65)

Add md tag to star output

---

src/app/main.ml
src/lib/common.ml
src/lib/gatk.ml
src/lib/muse.ml
src/lib/mutect.ml
src/lib/pipeline.ml
src/lib/reference_genome.ml
src/lib/reference_genome.mli
src/lib/run_environment.ml
src/lib/strelka.ml
src/lib/varscan.ml
src/lib/vcftools.ml
src/lib/virmid.ml

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/hammerlab/biokepi/68)

Ketrew 2.0.0 and more hooks to compile pipelines

---

_oasis
src/lib/mosaik.ml
src/lib/pipeline.ml
src/lib/run_environment.ml

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/hammerlab/biokepi/69)

Add the MOSAIK aligner

---

README.md

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/hammerlab/biokepi/74)

Clear up the README

---

_oasis
src/lib/common.ml

At the end of https://github.com/hammerlab/biokepi/pull/73 @smondet made some good requests for how we should generate the code. This PR adds those back into the document generating command.

Add documentation (2nd try)

---

src/lib/cufflinks.ml

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/hammerlab/biokepi/76)

Add sorting dependency to cufflinks

---

_oasis
src/lib/kallisto.ml
src/lib/reference_genome.ml
src/lib/reference_genome.mli
src/lib/run_environment.ml

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/hammerlab/biokepi/77)

Kallisto transcript quantification tool

---

.gitignore
Makefile

This fixes #80
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/hammerlab/biokepi/81)

Re-enable oredoc documentation generation

---

.merlin
.ocamlinit

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/hammerlab/biokepi/83)

Add developer files

---

src/lib/gatk.ml
src/lib/pipeline.ml

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/hammerlab/biokepi/91)

Allow Gatk.indel_realigner to be configured

---

src/lib/gatk.ml

Oops.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/hammerlab/biokepi/92)

Add spaces around args in GATK indel_realigner

---

src/lib/mutect.ml
src/lib/pipeline.ml

Fixes https://github.com/hammerlab/biokepi/issues/90
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/hammerlab/biokepi/93)

Allow MuTect to take parameters

---

src/lib/gatk.ml

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/hammerlab/biokepi/94)

Remove excess fmt string in IndelRealigner args

---

_oasis
src/lib/gatk.ml
src/lib/pipeline.ml
src/lib/tool_parameters.ml

Factored out Configuration into new top-level Tool_parameters
Fixes https://github.com/hammerlab/biokepi/issues/95
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/hammerlab/biokepi/97)

Add parameters to Gatk's Bqsr

---

opam/opam
src/lib/pipeline.ml
src/lib/stringtie.ml
tools/travis_ci_test.sh

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/hammerlab/biokepi/101)

Add stringtie to the pipeline API

---

src/lib/build_machine.ml
src/lib/download_reference_genomes.ml
src/lib/download_reference_genomes.mli
src/lib/reference_genome.ml
src/lib/reference_genome.mli
src/lib/region.ml
src/lib/run_environment.ml

This is #103 but works with Ketrew 2.0.0 so it is mergeable with `master`.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/hammerlab/biokepi/106)

Add mm10 mouse genome

---

src/lib/download_reference_genomes.ml

[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/hammerlab/biokepi/110)

Fix URL mm10 is pulled from

---

src/lib/mutect.ml

[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/hammerlab/biokepi/111)

Make DBSNP optional for MuTect

---

src/lib/download_reference_genomes.ml
src/lib/vcftools.ml
src/lib/workflow_utilities.ml

[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/hammerlab/biokepi/113)

Add mm10 dbSNP (INDEL & SNP)

---

src/lib/common.ml
src/lib/pipeline.ml
src/lib/reference_genome.ml
src/lib/reference_genome.mli
src/lib/stringtie.ml

Fixes for #104, #108, #116, #122.
@ihodes: I haven't tested Stringtie like this.
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/hammerlab/biokepi/123)

Small-ish various fixes

---

src/lib/samtools.ml
tools/travis_ci_test.sh

[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/hammerlab/biokepi/133)

Fix travis build and #130

---

src/lib/gatk.ml
src/lib/pipeline.ml

It is for issues #109 and #138.
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/hammerlab/biokepi/143)

Gatk: fix haplo and add mutect2

---

src/lib/samtools.ml

[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/hammerlab/biokepi/144)

Make `index_to_bai` fail on unsorted bams (#129)

---

src/lib/stringtie.ml

[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/hammerlab/biokepi/145)

Make Stringtie request sorted bams (fix #128)

---

src/lib/pipeline.ml

It is in `Pipeline.to_file_prefix`, now it's up to whoever defines the
datasets to to give different names to tumor and normal samples.
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/hammerlab/biokepi/147)

Remove `-normal`/`-tumor` suffixes

---

src/lib/mosaik.ml

[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/hammerlab/biokepi/149)

Fix use of read-2 in `Mosaik` (#148)

---

src/lib/build_machine.mli

[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/hammerlab/biokepi/153)

Spelling and word order

---

src/lib/run_environment.ml
src/lib/samtools.ml
src/lib/tool_providers.ml

Fixes https://github.com/hammerlab/biokepi/issues/167
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Review on Reviewable"/>](https://reviewable.io/reviews/hammerlab/biokepi/168)

Upgrade samtools from 1.1 to 1.3

---

src/lib/picard.ml

This is necessary for some Picard tools requiring contigs to appear in
the same order in both the reference and a VCF like dbSNP.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Review on Reviewable"/>](https://reviewable.io/reviews/hammerlab/biokepi/169)

Add Picard.sort_vcf

---

src/lib/reference_genome.ml

Also make sure all b38 releases are the same (79).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hammerlab/biokepi/171)

Add exome GTF to b37 decoy

---

_oasis
src/lib/biopam.ml
src/lib/conda.ml

Exposing `conda` very similarly to the way we expose `opam`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hammerlab/biokepi/173)

Conda and seq2HLA as demo

---

src/lib/samtools.ml

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hammerlab/biokepi/175)

samtools flagstat recipe

---

src/lib/run_environment.ml
src/lib/tool_providers.ml

(Haven't made sure this works yet)
Fixes https://github.com/hammerlab/biokepi/issues/165

Upgrade stringtie to 1.2.2

---

src/lib/pipeline.ml

a WIP.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hammerlab/biokepi/178)

Use a GADT to model the germline & somatic variant calling distinction

---

src/lib/run_environment.ml

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hammerlab/biokepi/188)

Spelling fixes in documentation.

---

src/lib/build_machine.ml
src/lib/run_environment.ml

This field doesn't serve a purpose.
This PR conflicts with the HLA one, I'll fix the other branch, which-ever branch gets merged first.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hammerlab/biokepi/197)

Remove ssh_name field from Machine.

---

src/lib/bwa.ml
src/lib/common.ml
src/lib/picard.ml
src/lib/pipeline.ml

Cf. #154 
Do not merge, I haven't tested yet.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hammerlab/biokepi/189)

Pass sample ID to `bwa {aln,mem}`

---

src/lib/gatk.ml
src/lib/pipeline.ml

This fixes issue #185.
Also, testing is still in progress.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hammerlab/biokepi/190)

Add option to map-reduce the indel-realigner

---

src/lib/hisat.ml
src/lib/kallisto.ml

Fixes #179
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hammerlab/biokepi/202)

Drop processors argument from indexing step

---

src/app/hla_typer.ml
src/lib/biopam.ml
src/lib/biopam.mli
src/lib/pipeline.ml
src/lib/seq2HLA.ml

I'm still testing how it works with the rest, in a big pipeline.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hammerlab/biokepi/199)

Some seq2hla fixes

---

src/lib/bedtools.ml
src/lib/samtools.ml

---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hammerlab/biokepi/198)

Add bedtools intersect

---

src/lib/pipeline.ml

This implements #203.
It depends on
[`hammerlab/ketrew#414`](https://github.com/hammerlab/ketrew/pull/414).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hammerlab/biokepi/205)

Add `Pipeline.Construct.add_tags`

---

src/lib/gatk.ml

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hammerlab/biokepi/212)

Make GATK.haplotype_caller a big program

---

src/lib/biopam.ml
src/lib/conda.ml
src/lib/optitype.ml

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hammerlab/biokepi/221)

Add OptiType invocation.

---

src/bfx_tools/samtools.ml

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hammerlab/biokepi/230)

Ask for more memory when running `samtools sort`

---

src/bfx_tools/star.ml

Complies with SAM spec (must have a RG specified) and ensures this works
with the downstream GATK.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hammerlab/biokepi/235)

Add @RG to star

---

src/bfx_tools/gatk.ml
src/bfx_tools/star.ml
src/pipeline_edsl/pipeline.ml

This adds configuration to STAR from the pipeline on down.
This also adds typed malformed read filters into the GATK configuration.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hammerlab/biokepi/237)

Add config to STAR and expand on GATK config

---

src/pipeline_edsl/pipeline.ml

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hammerlab/biokepi/239)

Add Optitype to the pipeline

---

src/bfx_tools/samtools.ml
src/pipeline_edsl/to_workflow.ml

For me, this "fixes" #240 (I mean we do everything we can ☺)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hammerlab/biokepi/241)

Samtools merge one bam

---

README.md
src/doc/Guide_to_the_code.md
src/doc/Use_the_demo.md
src/lib/biokepi.ml
src/pipeline_edsl/to_workflow.ml
tools/build-doc.sh
tools/ocamldoc-style.css

Of course there will be more, but this makes already a reasonably sized PR.
I've pushed there for now: http://wr.mondet.org/smondet/biokepi-doc/
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hammerlab/biokepi/242)

More documentation

---

src/bfx_tools/gatk.ml

This causes GATK to crash.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hammerlab/biokepi/243)

Remove empty args in GATk config

---

src/run_environment/reference_genome.ml

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hammerlab/biokepi/244)

Add exome annotation to mm10 reference

---

src/run_environment/reference_genome.ml

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hammerlab/biokepi/246)

Change mm10 to something with sane contig names

---

src/bfx_tools/seq2HLA.ml
src/pipeline_edsl/pipeline.ml
src/pipeline_edsl/to_workflow.ml

Should have included this with #248
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hammerlab/biokepi/253)

Add processors argument to seq2hla

---

src/examples/edsl_extension_register_result.ml
src/lib/biokepi.ml
src/pipeline_edsl/pipeline_library.ml
src/pipeline_edsl/to_workflow.ml
tools/build-doc.sh
tools/travis_ci_test.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hammerlab/biokepi/254)

TTFI-EDSL: Pipeline Library + 1 example extension

---

src/bfx_tools/optitype.ml
src/pipeline_edsl/pipeline.ml
src/pipeline_edsl/to_workflow.ml

Use fastq workflow_node in lieu of the r1/r2 components of one, and
correctly depend on it.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hammerlab/biokepi/257)

Fix optitype

---

src/bfx_tools/star.ml

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hammerlab/biokepi/259)

Add overhang parameter to STAR

---

src/app/hla_typer.ml
src/app/main.ml
src/bfx_tools/bedtools.ml
src/bfx_tools/bwa.ml
src/bfx_tools/cufflinks.ml
src/bfx_tools/gatk.ml
src/bfx_tools/hisat.ml
src/bfx_tools/mosaik.ml
src/bfx_tools/muse.ml
src/bfx_tools/mutect.ml
src/bfx_tools/picard.ml
src/bfx_tools/samtools.ml
src/bfx_tools/seq2HLA.ml
src/bfx_tools/star.ml
src/bfx_tools/strelka.ml
src/bfx_tools/stringtie.ml
src/bfx_tools/virmid.ml
src/environment_setup/build_machine.ml
src/environment_setup/build_machine.mli
src/examples/edsl_extension_register_result.ml
src/pipeline_edsl/pipeline.ml
src/pipeline_edsl/to_workflow.ml
src/run_environment/machine.ml

Long discussed clean-up that had to be done.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hammerlab/biokepi/264)

Processors in/from the machine

---

src/bfx_tools/optitype.ml

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hammerlab/biokepi/250)

Add path to optitype product

---

src/app/hla_typer.ml
src/bfx_tools/hisat.ml
src/bfx_tools/optitype.ml
src/bfx_tools/seq2HLA.ml
src/environment_setup/biopam.ml
src/environment_setup/biopam.mli
src/environment_setup/build_machine.ml
src/environment_setup/conda.ml
src/environment_setup/conda.mli
src/environment_setup/tool_providers.ml
src/run_environment/machine.ml
src/test/all_downloads.ml

This also adds a bunch of tests in `all_downloads.ml`:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hammerlab/biokepi/266)

Clean-up Tool setup

---

README.md
src/environment_setup/biopam.mli

The build of the documentation is still kinda broken at least it does not fail now.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hammerlab/biokepi/274)

Minor documentation fixes

---

src/environment_setup/biopam.ml
src/environment_setup/biopam.mli
src/test/all_downloads.ml

Tested with `hlarp`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hammerlab/biokepi/275)

`opam pin` in `Biopam`

---

src/bfx_tools/fastqc.ml
src/environment_setup/tool_providers.ml
src/run_environment/machine.ml

This will resolve #158.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hammerlab/biokepi/276)

Add support for fastqc tool

---

src/environment_setup/tool_providers.ml
src/pipeline_edsl/optimization_framework.ml
src/pipeline_edsl/semantics.ml
src/pipeline_edsl/to_json.ml
src/pipeline_edsl/to_workflow.ml
src/test/ttfi_pipeline.ml

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hammerlab/biokepi/277)

Add FASTQC to the TTFI EDSL

---

src/run_environment/reference_genome.ml

79 -> 84.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hammerlab/biokepi/280)

bump mm10's GTF version (fixes #279)

---

src/bfx_tools/bedtools.ml

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hammerlab/biokepi/281)

Add unique flag to bedtools intersect defaults

---

src/bfx_tools/fastqc.ml
src/environment_setup/tool_providers.ml

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hammerlab/biokepi/282)

Fix some issues with Fastqc

---

src/bfx_tools/seq2HLA.ml
src/pipeline_edsl/to_workflow.ml

We want to manipulate these files later in the pipeline.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hammerlab/biokepi/284)

Add particular paths to seq2HLA results

---

src/bfx_tools/picard.ml
src/environment_setup/tool_providers.ml

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hammerlab/biokepi/285)

Fix little annoyances

---

.travis.yml
src/examples/edsl_extension_register_result.ml
src/lib/biokepi.ml
src/pipeline_edsl/pipeline_library.ml
src/pipeline_edsl/to_dot.ml
src/test/ttfi_pipeline.ml
tools/travis_ci_test.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hammerlab/biokepi/288)

EDSL improvements

---

src/bfx_tools/picard.ml

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hammerlab/biokepi/291)

Use better default for `markdup_dups` tmp-dir

---

src/bfx_tools/isovar.ml
src/bfx_tools/pyensembl.ml
src/bfx_tools/topiary.ml
src/bfx_tools/vcfannotatepolyphen.ml
src/environment_setup/biopam.ml
src/environment_setup/conda.ml
src/environment_setup/conda.mli
src/environment_setup/download_reference_genomes.ml
src/environment_setup/python_package.ml
src/environment_setup/tool_providers.ml
src/pipeline_edsl/optimization_framework.ml
src/pipeline_edsl/semantics.ml
src/pipeline_edsl/to_json.ml
src/pipeline_edsl/to_workflow.ml
src/run_environment/machine.ml
src/run_environment/reference_genome.ml
src/run_environment/reference_genome.mli
src/run_environment/workflow_utilities.ml

This is my first attempt to provide a generalized way to install Python tools from packages/repos. I assume the python module is going to change quite a lot as we move forward with this; but, this should cover the very basic use case. I used [vcf-annotate-polyphen](https://github.com/hammerlab/vcf-annotate-polyphen) for demo purposes here.
I know that there is still a lot to improve here, but I decided to create this PR anyway to collect your early feedback and iterate over these choices as soon as possible. It would be great if you can CR my coding style as well (as I am pretty new to this game).
In the meantime, I might factor some of the conda stuff out to make use of `Python_package` or continue adding Python tools to this PR.
cc: @rleonid @ihodes @smondet
---
This change is [<img …

Support for installing Python tool packages (e.g. vcf-annotate-polyphen)

---

src/pipeline_edsl/to_json.ml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hammerlab/biokepi/293)

Fix Topiary's `To_json` and `To_dot` outputs

---

src/bfx_tools/bedtools.ml
src/pipeline_edsl/to_workflow.ml
src/run_environment/workflow_utilities.ml

Just a few argument renamings.
Depends on https://github.com/hammerlab/ketrew/pull/447
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hammerlab/biokepi/295)

Update to `Ketrew.EDSL` API changes

---

src/bfx_tools/vaxrank.ml
src/environment_setup/python_package.ml
src/pipeline_edsl/optimization_framework.ml
src/pipeline_edsl/semantics.ml
src/pipeline_edsl/to_json.ml
src/pipeline_edsl/to_workflow.ml

hello vaxrank!
fixes #297.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hammerlab/biokepi/302)

Add support for vaxrank

---

src/bfx_tools/vaxrank.ml
src/pipeline_edsl/to_workflow.ml
src/test/ttfi_pipeline.ml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hammerlab/biokepi/307)

Fix output-paths for python-tools and build of one test

---

src/environment_setup/download_reference_genomes.ml
src/run_environment/reference_genome.mli

Looks like there were some pieces missing in #308 as I needed to add to the `mli` file and then make the reference available for download as well. This fixes that.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hammerlab/biokepi/310)

Add download hg38

---

src/pipeline_edsl/optimization_framework.ml
src/pipeline_edsl/semantics.ml
src/pipeline_edsl/to_json.ml
src/pipeline_edsl/to_workflow.ml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hammerlab/biokepi/304)

Add Flagstat to the TTFI

---

src/environment_setup/conda.ml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hammerlab/biokepi/313)

Improve Conda installation

---

src/run_environment/reference_genome.ml

Sorry - one more fix on this. The previous dbsnp file had the wrong contig names.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hammerlab/biokepi/314)

Fix dbsnp link for hg38

---

src/environment_setup/python_package.ml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hammerlab/biokepi/319)

Use the version string in the Conda environment

---

src/bfx_tools/gatk.ml

Still not sure this should be an option, but right now hoping to get a pipeline moving.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hammerlab/biokepi/323)

Add mutect2 config without cosmic

---

src/pipeline_edsl/optimization_framework.ml
src/pipeline_edsl/pipeline_library.ml
src/pipeline_edsl/semantics.ml
src/pipeline_edsl/to_json.ml
src/pipeline_edsl/to_workflow.ml
src/test/ttfi_pipeline.ml

Cf. #322.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hammerlab/biokepi/326)

Refactor EDSL input + add HTTP(S) URLs

---

src/pipeline_edsl/optimization_framework.ml
src/pipeline_edsl/pipeline_library.ml
src/pipeline_edsl/pipeline_library.mli
src/pipeline_edsl/semantics.ml
src/pipeline_edsl/to_json.ml
src/pipeline_edsl/to_workflow.ml
src/test/ttfi_pipeline.ml

Depends on #326.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hammerlab/biokepi/327)

Input.t to bwa_mem_opt

---

tools/docker/run/Dockerfile
tools/docker/run/README.md

Cf. https://hub.docker.com/r/hammerlab/biokepi-run/
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hammerlab/biokepi/328)

Add a Dockerfile for a “run box”

---

src/app/input_gen.ml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hammerlab/biokepi/329)

Make clear that the sample-name be unique

---

src/pipeline_edsl/to_dot.ml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hammerlab/biokepi/334)

Avoid hash-collision in `EDSL.To_dot`

---

src/bfx_tools/vaxrank.ml
src/environment_setup/python_package.ml
src/pipeline_edsl/optimization_framework.ml
src/pipeline_edsl/semantics.ml
src/pipeline_edsl/to_json.ml
src/pipeline_edsl/to_workflow.ml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hammerlab/biokepi/324)

Vaxrank can now take multiple VCFs

---

tools/docker/run/Dockerfile

One could use in every call in the meantime:
Program.(sh "apt-get install --yes wget" && p)
Fixing #336.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hammerlab/biokepi/337)

Rewrite`Dockerfile`

---

tools/docker/run/Dockerfile

This just makes it simpler to use the Docker container interactively.
(don't need to override `--entrypoint`)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hammerlab/biokepi/340)

More dockerfile improvements

---

src/environment_setup/python_package.ml
src/pipeline_edsl/optimization_framework.ml
src/pipeline_edsl/semantics.ml
src/pipeline_edsl/to_json.ml
src/pipeline_edsl/to_workflow.ml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hammerlab/biokepi/342)

Add bedtools intersect for VCF files to TTFI

---

src/bfx_tools/topiary.ml
src/bfx_tools/vaxrank.ml
src/environment_setup/build_machine.ml
src/environment_setup/build_machine.mli
src/environment_setup/netmhc.ml
src/environment_setup/tool_providers.ml
src/run_environment/workflow_utilities.ml

Fixes #287
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hammerlab/biokepi/344)

add support for installing relevant NetMHC tools

---

.travis.yml
src/examples/edsl_extension_register_result.ml
tools/travis_ci_test.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hammerlab/biokepi/348)

Add OCaml 4.03.0 to the travis builds

---

src/pipeline_edsl/pipeline_library.ml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hammerlab/biokepi/349)

Give fragments default names in the Input deriver

---

src/bfx_tools/gatk.ml
src/pipeline_edsl/to_workflow.ml
src/run_environment/common.ml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hammerlab/biokepi/350)

Control filename lengths

---

tools/docker/run/Dockerfile
tools/docker/run/README.md

Yet another follow up to #347 and #287.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hammerlab/biokepi/351)

add gawk as a dependency (for NetMHC stuff)

---

src/bfx_tools/vaxrank.ml

fixes #356
Question: will this fail if the BAM is unsorted? Does Vaxrank expect the BAM to be sorted? @iskandr

Vaxrank depends on the input BAM having a BAI

---

src/bfx_tools/pyensembl.ml
src/environment_setup/python_package.ml
src/run_environment/reference_genome.ml

Bump Ensembl release to 85 for mm10

Update PyEnsembl and Vaxrank

---

src/environment_setup/python_package.ml

@ihodes I remember you fiddling with this. Any reason why we haven't done this yet?
cc: @iskandr @julia326

Python-tools: bump vaxrank version

---

src/pipeline_edsl/to_workflow.ml
src/run_environment/common.ml

Also rename the suffix for bedtools intersect in the TTFI

Fix the naming hash comparing function types

---

OMakeroot

Same as https://github.com/hammerlab/ketrew/pull/503

Fix build with omake 0.10.1

---

src/bfx_tools/vaxrank.ml
src/environment_setup/python_package.ml

fixes https://github.com/hammerlab/biokepi/issues/367

Update Vaxrank to 0.3.0 and its arguments/defaults

---

src/bfx_tools/sambamba.ml
src/environment_setup/tool_providers.ml
src/pipeline_edsl/optimization_framework.ml
src/pipeline_edsl/semantics.ml
src/pipeline_edsl/to_json.ml
src/pipeline_edsl/to_workflow.ml
src/run_environment/machine.ml

Add Sambamba

---

src/environment_setup/tool_providers.ml

Because the tar.bz2 contains no directory, we shouldn't try to cd into it.

Fix Sambamba install

---

src/pipeline_edsl/semantics.ml
src/pipeline_edsl/to_workflow.ml
src/run_environment/workflow_utilities.ml

Fixing #322 and #404.
(and https://github.com/hammerlab/epidisco/issues/6 *side-effectly*)

Better input management in the EDSL

---

src/bfx_tools/cufflinks.ml
src/bfx_tools/kallisto.ml
src/pipeline_edsl/optimization_framework.ml
src/pipeline_edsl/semantics.ml
src/pipeline_edsl/to_json.ml
src/pipeline_edsl/to_workflow.ml

fixes https://github.com/hammerlab/biokepi/issues/139
fixes https://github.com/hammerlab/biokepi/issues/263

Add kallisto cufflinks to ttfi

---

src/run_environment/reference_genome.ml

Use hammerlab link to a sorted mm10 fa

---

src/bfx_tools/picard.ml
src/pipeline_edsl/optimization_framework.ml
src/pipeline_edsl/semantics.ml
src/pipeline_edsl/to_json.ml
src/pipeline_edsl/to_workflow.ml

for https://github.com/hammerlab/epidisco/issues/167#issuecomment-283806812

Add Picard.reorder_sam

---

src/app/input_gen.ml

The change is still compatible with previous versions.

Fix build with Cmdliner 1.0.0

---

src/bfx_tools/bwa.ml
src/pipeline_edsl/common_pipelines.ml

Fixes #445.
I might have done something stupid with the way I use modules/functors since I barely use them. Let me know if the coding style looks off.

Separate bwa configs for mem and aln sub-methods

---

src/bfx_tools/star.ml

Our tools with automatically sort the BAM if needed

STAR aligner shouldn't do sorting; does in-memory

---

src/bfx_tools/bcftools.ml
src/bfx_tools/delly2.ml
src/bfx_tools/somaticsniper.ml
src/environment_setup/tool_providers.ml
src/pipeline_edsl/optimization_framework.ml
src/pipeline_edsl/semantics.ml
src/pipeline_edsl/to_json.ml
src/pipeline_edsl/to_workflow.ml
src/run_environment/machine.ml

Waiting on it to run to make sure it's working
Fixes https://github.com/hammerlab/biokepi/issues/454
Fixes https://github.com/hammerlab/biokepi/issues/456

Add delly2

---

src/run_environment/reference_genome.ml

Fixing b37 Broad links.
