hammerlab/biokepi

src/app/main.ml
src/lib/biokepi_common_pipelines.ml
src/lib/biokepi_pipeline.ml
src/lib/biokepi_target_library.ml

This should make it easier to add somatic variant callers.
(i.e. this kind of dev but somatic
https://github.com/hammerlab/biokepi/compare/add-haplotype-caller)
- a new Biokepi variant caller would just have to create a function in `Biokepi_pipeline.Construct`
- anyone can create that kind of step without having to modify the library (as long as they comply with the API in `Somatic_variant_caller.t`)
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/hammerlab/biokepi/9)

Factor somatic variant callers in the same GADT variant

---

src/lib/biokepi_pipeline.ml
src/lib/biokepi_region.ml
src/lib/biokepi_run_environment.ml

This adds an alternative B37 reference that contains decoy sequences for improved alignment and epstein-barr virus sequence
More details on the differences are here: 
https://wiki.dnanexus.com/Scientific-Notes/human-genome#What-exactly-is-%22human-DNA%22%3F
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/hammerlab/biokepi/21)

Add b37 reference with decoy sequences

---

src/lib/biokepi_pipeline.ml
src/lib/biokepi_util_targets.ml

- Add `-nt` option to IndelRealaignment
- Add `-nct` to BQSR
Also added a sorted bam requirement to mark duplicates
This is based on the suggested flags from http://gatkforums.broadinstitute.org/discussion/1975/how-can-i-use-parallelism-to-make-gatk-tools-run-faster

Adding multi-threading option to GATK tools

---

src/lib/biokepi_util_targets.ml

#39 created an issue with `samtools sort`
Because of the `""` in the arguments the command became `'samtools' 'sort' '' '-@4' ...` and `samtools` could not parse the empty argument
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/hammerlab/biokepi/43)

Fix sort by coordinate

---

src/app/main.ml
src/lib/biokepi_common.ml
src/lib/biokepi_pipeline.ml
src/lib/biokepi_reference_genome.ml
src/lib/biokepi_reference_genome.mli
src/lib/biokepi_run_environment.ml
src/lib/biokepi_somatic_targets.ml
src/lib/biokepi_target_library.ml
src/lib/biokepi_util_targets.ml

This is an experiment to create a stricter EDSL on top of Ketrew; the changes
imply a hige refactoring that does not change any semantics.
It's a bit what was there: https://github.com/hammerlab/ketrew/pull/182 so it may be a staging area before pushing upstream,
Now the `bantofastq` workflow-node “returns” a proper FASTQ pair-of-files or single-file.
This in the same time updtates to the latests version of Ketrew's API.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/hammerlab/biokepi/45)

Experiment:  `Common.KEDSL`

---

src/lib/picard.ml

Looks like it is a commonly known problem that Picard ignores the TMP_DIR (or it's reset at somepoint) and providing the java tmpdir is more effective
See:
https://bitbucket.org/galaxy/galaxy-central/pull-request/28/specify-java-temp-directory-for-picard/diff
http://sourceforge.net/p/samtools/mailman/message/27300266/
http://dev.list.galaxyproject.org/incorrect-tmp-dir-handling-in-picard-AddOrReplaceReadGroups-td4529840.html
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/hammerlab/biokepi/51)

Specify the tmpdir for java as well for picard

---

src/lib/pipeline.ml

- There can be multiple somatic variant calling runs with the same normal file, but different tumor files.  Naming the run after the normal file would create a file name collision.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/hammerlab/biokepi/54)

Name bam pair after tumor file

---

src/lib/common.ml
src/lib/pipeline.ml

Not sure if you want to merge this @smondet or if you will find a better solution, but filed the PR to record the problem and possible fix.
The single-end workflow node ends up in a loop by having a dependency with the same success condition.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/hammerlab/biokepi/60)

Remove equivalence from single end

---

src/lib/star.ml

This actually undoes something from #65 where the output file name was change.  Part of that filename comes automatically from STAR, so I reverted that and added a comma.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/hammerlab/biokepi/66)

Fix STAR output path

---

src/lib/gatk.ml

GATK HaplotypeCaller fails on DNA BAM files with CIGAR N - this flag skips those lines.  It would be nice to restrict this to BAM files that only have `~contains \`DNA` is that possible?
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/hammerlab/biokepi/67)

add filter_reads_with_N_cigar to GATK HC

---

Makefile
_oasis
src/lib/common.ml
src/lib/muse.ml

I took out the call to `oredoc`, happy to add that back when `oredoc` is easier to access. This should address #72 as there is now `gh-pages` branch being [served](https://github.com/hammerlab/biokepi). But I think we should file separate issues for improving documentation.

Add documentation

---

src/lib/mutect.ml

This fixes #89, it allows one to choose whether to depend on the COSMIC
DB from the `Configuration.t`.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/hammerlab/biokepi/107)

Make COSMIC optional for Mutect

---

src/lib/strelka.ml

This mirrors the more user-friendly MuTect module's approach to configuration.
(Sorry for also nixing some whitespace in the same commit; only a few though!)
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/hammerlab/biokepi/114)

Set a default configuration for Strelka

---

src/lib/common.ml
src/lib/gatk.ml
src/lib/pipeline.ml

This is for #125.
The function `Gatk.indel_realigner` can take an arbitrary list of bams.
At the `Pipeline.t` level, this is, for now, implemented as an optional "compiler optimization."
It will detect pipelines of the form `somatic_variant_caller (indel |> bqsr, indel |> bqsr)` and run the indel-realigner on both the tumor and normal together and then before re-split for bqsr.
I haven't properly tested yet (I've generated the ketrew pipelines and looked at them, but haven't run GATK & co because I'm cluster-orphan these days), but while this gets run, having more eyes on the code would be nice, hence the PR :)
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/hammerlab/biokepi/150)

Indel-realignment on multiple bams

---

src/lib/download_reference_genomes.ml
src/lib/vcftools.ml

This adds a `vcf-sort` step after downloading MM10's DbSNP's SNPs and INDELs.
So this is a fix for #134 to run BQSR on MM10, but not for #135 for which we need
to come up with decent semantics for `#dbsnp` and a consistent API.
I've run
[`src/test/all_downloads.ml`](https://github.com/hammerlab/biokepi/blob/master/src/test/all_downloads.ml)
and the result looks sorted.
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/hammerlab/biokepi/152)

Add sorting of DbSNP VCFs

---

src/lib/gatk.ml
src/lib/pipeline.ml

Now that I have a cluster, could do more tests:
- GATK's indel-realigner with `--nWayOut` also does a `basename` on the input bams so it outputs to the “current” directory. Hence had to `cd` there to have proper file paths.
- There was a bug in `Pipeline.to_file_prefix` that the optmization pass exhibited.
- There was a 99.9% silent bug in `Gatk.bqsr` with the path to the `-recal_data.table` file that I saw while reading the code.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Review on Reviewable"/>](https://reviewable.io/reviews/hammerlab/biokepi/161)

Do various fixes

---

src/lib/pipeline.ml
src/lib/samtools.ml

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Review on Reviewable"/>](https://reviewable.io/reviews/hammerlab/biokepi/162)

Optimize aligners over FASTQ fragments on-demand

---

src/lib/tool_providers.ml

It seems that since the last time we changed all that code, we have tested this
one only with Ketrew servers that have a shared file-system with the host that
runs the jobs.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hammerlab/biokepi/170)

Fix missing `~host` in `get_broad_jar`

---

src/lib/build_machine.ml
src/lib/build_machine.mli
src/lib/bwa.ml
src/lib/cufflinks.ml
src/lib/cycledash.ml
src/lib/download_reference_genomes.ml
src/lib/download_reference_genomes.mli
src/lib/hisat.ml
src/lib/kallisto.ml
src/lib/mosaik.ml
src/lib/mutect.ml
src/lib/run_environment.ml
src/lib/somaticsniper.ml
src/lib/star.ml
src/lib/strelka.ml
src/lib/stringtie.ml
src/lib/varscan.ml
src/lib/vcftools.ml
src/lib/virmid.ml
src/lib/workflow_utilities.ml
src/test/all_downloads.ml

The idea is that users of the `Make_fun.t` functions express their needs with a
`~requirements` argument.
Both the `Make_fun` and `Machine` modules provide functions with default
values.
The `Make_fun.Requirement.t` variants are of course just a first stab to be
refined later (and some cases are not used anywhere).
This “fixes” #163.
We can start taking notes when we run tools, so that they can give a better
estimate of their memory requirements (cf. #166).
I came across #179 but did not fix it yet (I actually don't really know these
tools).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hammerlab/biokepi/180)

Implement “requirements” for `Machine.run_program`

---

src/lib/picard.ml

On pretty standard data, mark-dups went way over 5 GB which is our current
heuristic.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hammerlab/biokepi/196)

Make `Picard.mark_duplicates` a “big” program

---

src/lib/strelka.ml

Now we get just the two samples that we expect, TUMOR and NORMAL, in the header.
fixes https://github.com/hammerlab/biokepi/issues/204
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hammerlab/biokepi/206)

Merge Indels and SNVs properly for Strelka

---

src/lib/biopam.ml
src/lib/biopam.mli
src/lib/conda.ml
src/lib/conda.mli

The function `wrap_environment` was working only because Conda's deactivation
doesn't really work (at least it seems so).
This is kind-of a different solution from #207.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hammerlab/biokepi/208)

Make `Conda` environment only “activable”

---

src/lib/common.ml
src/lib/gatk.ml
src/lib/mosaik.ml
src/lib/muse.ml
src/lib/mutect.ml
src/lib/picard.ml
src/lib/pipeline.ml
src/lib/samtools.ml
src/lib/somaticsniper.ml
src/lib/star.ml
src/lib/strelka.ml
src/lib/stringtie.ml
src/lib/varscan.ml
src/lib/virmid.ml

This implements #24.
The function `KEDSL.transform_bam` also makes many workflows more readable and
safer.
We can later add a function `check_bams` that verifies at least one property: all the bams involved have the same ref-build (e.g. `normal` and `tumor` for variant callers; or the lists for bam-merging or indel-realigning).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hammerlab/biokepi/214)

Make `reference_build` part of `bam_file`

---

OMakeroot
tools/build-doc.sh

This moves the build to the script `tools/build-doc.sh` to do the heavy duty.
It adds a webpage that includes 3 SVG dependency graphs from OCamlDoc's `-dot`
output.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hammerlab/biokepi/216)

Improve the build of the documentation

---

src/lib/pipeline.ml

The one-byte mistake was giving two normal bams to somatic variant callers.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hammerlab/biokepi/217)

Fix bug introduced in PR #205

---

src/lib/hisat.ml
src/lib/pipeline.ml
src/lib/run_environment.ml
src/lib/tool_providers.ml

This has been tested insofar in that it correctly produces the index and proper hisat2 command (alongside with hisat1) but the hisat2 alignment has not completed. I figured it was worth reviewing in the meantime
This follows the model we discussed previously:
- Creates a versioned Hisat in `run_environment.ml`
- Add a version argument to `hisat` in `tool_providers.ml` as well as putting the version in the install path
- Adds config to hisat to switch between versions
Let me know any critiques or if anything can be improved.
cc @smondet @ihodes
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hammerlab/biokepi/219)

Adding Hisat2

---

OMakeroot
src/app/main.ml
src/bfx_tools/bwa.ml
src/lib/biokepi.ml
src/pipeline_edsl/common_pipelines.ml
src/pipeline_edsl/pipeline.ml
src/pipeline_edsl/semantics.ml
src/pipeline_edsl/to_display.ml
src/pipeline_edsl/to_display.mli
src/pipeline_edsl/to_workflow.ml
src/run_environment/common.ml
src/test/ttfi_pipeline.ml

This is the beginning of the implementation of the Typed-Tagless-Final-Interpreter -based pipeline EDSL.
It is far from ready for use but since there are some changes in `Common` and `Bwa` it's nice to get it merged.
It makes also a smaller peer review :)
Names may still change, open to suggestions (e.g. `Biokepi.EDSL` → that's maybe not specific enough?).
For now there is:
- `Semantics`: module type that defines the EDSL.
- `To_display` interpreter that compiles to `SmartPrint.t`
- `To_workflow`: interpreter that compiles to Ketrew workflows (of `Biokepi.Tools.*` nodes)
- `src/test/ttfi_pipeline.ml`: a test that will grow more and more complex pipelines
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" …

TTFI Pipeline -- First Blood

---

src/bfx_tools/bwa.ml
src/bfx_tools/cufflinks.ml
src/bfx_tools/gatk.ml
src/bfx_tools/hisat.ml
src/bfx_tools/kallisto.ml
src/bfx_tools/mosaik.ml
src/bfx_tools/mutect.ml
src/bfx_tools/optitype.ml
src/bfx_tools/picard.ml
src/bfx_tools/somaticsniper.ml
src/bfx_tools/star.ml
src/bfx_tools/strelka.ml
src/bfx_tools/stringtie.ml
src/bfx_tools/varscan.ml
src/bfx_tools/virmid.ml
src/run_environment/machine.ml

This fixes #213.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hammerlab/biokepi/234)

Add support for “self-identification”

---

src/lib/biokepi.ml
src/pipeline_edsl/optimization_framework.ml
src/pipeline_edsl/semantics.ml
src/pipeline_edsl/to_display.ml
src/pipeline_edsl/to_dot.ml
src/pipeline_edsl/to_json.ml
src/pipeline_edsl/to_workflow.ml
src/pipeline_edsl/transform_applications.ml
src/run_environment/common.ml
src/test/ttfi_pipeline.ml

New things:
- Compilers `To_json` and `To_dot`
- Generic `Optimization_framework` (from QueL)
- One optimization pass that has mostly “display-value”
Not sure if `Biokepi.EDS.Transform.Beta_reduce` can be called like that. This is what the test outputs:
Pipeline:
Pipeline with `Transform_applications` applied:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hammerlab/biokepi/236)

TTFI-pipeline: 2nd strike

---

OMakeroot
src/pipeline_edsl/pipeline.ml
tools/build-doc.sh

The script `./tools/build-doc.sh` now generates “big” modules that are what the
“pack” option does.
The signature of one function in `./src/pipeline_edsl/pipeline.ml` had to be
forced so that `ocamlc -i` can generate valid code.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hammerlab/biokepi/238)

Hack better build for the documentation

---

src/pipeline_edsl/pipeline.ml

Updating the `seq2HLA` pipeline to run on fastqs from BAMs. Let me know if there was a better way to achieve this.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hammerlab/biokepi/248)

Allow seq2HLA to run on Bam_to_fastq 

---

src/bfx_tools/gatk.ml
src/bfx_tools/hisat.ml
src/bfx_tools/muse.ml
src/bfx_tools/mutect.ml
src/bfx_tools/picard.ml
src/bfx_tools/somaticsniper.ml
src/bfx_tools/strelka.ml
src/bfx_tools/virmid.ml
src/environment_setup/tool_providers.ml
src/lib/biokepi.ml
src/pipeline_edsl/common_pipelines.ml
src/pipeline_edsl/optimization_framework.ml
src/pipeline_edsl/pipeline.ml
src/pipeline_edsl/semantics.ml
src/pipeline_edsl/to_display.ml
src/pipeline_edsl/to_dot.ml
src/pipeline_edsl/to_json.ml
src/pipeline_edsl/to_workflow.ml
src/pipeline_edsl/transform_applications.ml
src/run_environment/common.ml
src/run_environment/machine.ml
src/test/ttfi_pipeline.ml

Ported everything in `Pipeline.t` to `Biokepi.EDSL`.
The test is now calling all the functions in `Semantics` in a single workflow, with a lot of `lambda`/`applly` etc.
It makes pretty crazy workflows, and the serialization of 
`Pipeline_1(Biokepi.EDSL.Transform.Apply_functions(Biokepi.EDSL.Compile.To_dot)).run`
gets `SmartPrint` into a `Stack_overflow` (on my laptop / everything else is fine).
So I had to run the test [with](http://stackoverflow.com/questions/31028681/ocamlrunparam-does-not-affect-stack-size): `ulimit -s 20000 ; OCAMLRUNPARAM=b ./biokepi-test-ttfi-pipeline`
It gets giant pictures:
- [pipeline-1](https://cloud.githubusercontent.com/assets/617111/14694668/b5378214-0738-11e6-8ed4-a6f99ff21b48.png)
- [pipeline-1-beta-ds](https://cloud.githubusercontent.com/assets/617111/14694 …

TTFI, the third

---

src/examples/edsl_extension_register_result.ml
src/pipeline_edsl/optimization_framework.ml
src/pipeline_edsl/semantics.ml
src/pipeline_edsl/to_json.ml
src/pipeline_edsl/to_workflow.ml
src/test/ttfi_pipeline.ml

This was an oversight in #256; now the variant callers take one `unit`
argument.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hammerlab/biokepi/258)

Make the optional arguments truly optional

---

src/pipeline_edsl/pipeline.ml
src/pipeline_edsl/to_workflow.ml
src/run_environment/common.ml

The implementation of the `#r1` and `#r2` methods was cutting the
dependency chain. Now the “product-level” methods return products and
there are separate functions at the “node-level” which preserve
dependencies.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hammerlab/biokepi/289)

Fix destructuring of FASTQ reads

---

src/pipeline_edsl/to_workflow.ml

This is in `EDSL.To_workflow`, a compiler option decides whether to
copy/link the input files to the work-directory.
This should fix #112 in the context of `Biokepi.EDSL`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hammerlab/biokepi/290)

Allow link/copy of input files

---

OMakeroot
src/pipeline_edsl/pipeline_library.ml
src/pipeline_edsl/pipeline_library.mli
src/test/edsl_input_json.ml

The idea is to have a more durable, versioned JSON format and parse it
manually to an `Input.t`.
There is a test: `src/test/edsl_input_json.ml`; calling
`./biokepi-edsl-input-json print` additionally shows some examples:
Example "1":
```````````````json
{
"Biokepi_input_v0": {
"Fastq": { "sample-name": "Sample1", "fragments": [] }
}
}
```````````````
Example "2":
```````````````json
{
"Biokepi_input_v0": {
"Fastq": {
"sample-name": "Sample2",
"fragments": [
{
"fragment-id": "frg1",
"data": { "PE": { "R1": "frg1R1.fastq", "R2": "frg1R2.fastq" } }
},
{ "fragment-id": "frg2", "data": { "SE": "frg2.fastq" } },
{
"fragment-id": null,
"data": {
"Bam": {
"kind": "PE",
"sorting": "coordinate",
"reference-genome": "b37",
"path": "n2.bam"
}
}
}
]
}
}
}
```````````````
Example "3": …

Reimplement `EDSL.Library.Input.{of,to}_yojson`

---

src/lib/biokepi.ml
src/pipeline_edsl/pipeline_library.mli

The goal is to make extensions easier again (types were hidden in recent PRs).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hammerlab/biokepi/298)

Expose a few types in the EDSL API

---

src/bfx_tools/topiary.ml
src/pipeline_edsl/optimization_framework.ml
src/pipeline_edsl/semantics.ml
src/pipeline_edsl/to_json.ml
src/pipeline_edsl/to_workflow.ml

This creates a new functions in the EDSL that is used to input MHC
Alleles for Topiary.
One can give a file name; or input directly allele names.
This is a follow up to #268.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hammerlab/biokepi/300)

Add `EDSL.mhc_alleles` input function

---

src/bfx_tools/bedtools.ml
src/bfx_tools/picard.ml
src/pipeline_edsl/optimization_framework.ml
src/pipeline_edsl/pipeline.ml
src/pipeline_edsl/pipeline_library.ml
src/pipeline_edsl/semantics.ml
src/pipeline_edsl/to_json.ml
src/pipeline_edsl/to_workflow.ml
src/run_environment/common.ml

This adds `sample_name` as a property of a BAM similar to fastq instead of carrying around a sample name.
Some of the pipeline aspects were a bit confusing, but this should have the same semantics. Are so many definitions of `bam_to_fastq` needed, seemed to have to edit this in a lot of places?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hammerlab/biokepi/305)

add sample_name to bam_file

---

src/bfx_tools/isovar.ml
src/bfx_tools/pyensembl.ml
src/bfx_tools/topiary.ml
src/bfx_tools/vaxrank.ml
src/environment_setup/build_machine.ml
src/environment_setup/build_machine.mli
src/environment_setup/python_package.ml
src/run_environment/machine.ml

So that each PyGenomics tool can use the same shared cached files if necessary.
More information on setting up the cache folder: https://github.com/hammerlab/pyensembl#cache-location
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hammerlab/biokepi/303)

Force PyEnsembl to cache into a shared location

---

src/environment_setup/download_reference_genomes.ml
src/run_environment/reference_genome.ml
src/run_environment/reference_genome.mli

The older links were broken, this uses the GATK provided bundle, but this is technically hg38 (meaning the contig are `chr` prefixed.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hammerlab/biokepi/308)

Update links to use broad hg38 bundle

---

OMakeroot
src/app/input_gen.ml
src/pipeline_edsl/pipeline_library.ml
src/pipeline_edsl/pipeline_library.mli
src/run_environment/common.ml

New executable biokepi-input-generator which takes a host and a dir of
fastq.gz and generates JSON serialization of Input.t for input into
Pipelines.ts.
Library supporting this at Biokepi.EDSL.Library.Input.Derive
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hammerlab/biokepi/311)

Add Input.t generation utilities

---

src/bfx_tools/igvxml.ml
src/environment_setup/biopam.ml
src/run_environment/machine.ml

This version works only with `b37decoy` and `mm10` (tool's choice).
But it works™ :)
I didn't add to the TTFI EDSL because I don't see the use case.
Also, the results depends on the paths not on the contents of the files at that path (they can run even if they don't exist), so the tool does not depend on the bam/vcf products.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hammerlab/biokepi/316)

Add igvxml

---

src/bfx_tools/bwa.ml
src/pipeline_edsl/optimization_framework.ml
src/pipeline_edsl/semantics.ml
src/pipeline_edsl/to_json.ml
src/pipeline_edsl/to_workflow.ml

Cf. #29.
I've tested the `Tools.Bwa.mem_align_to_bam` function but not yet the TTFI
version.
Instead of augmenting the current `bwa_mem` it is added as a new one:
```ocaml
val bwa_mem_opt:
?configuration: Biokepi_bfx_tools.Bwa.Configuration.Mem.t ->
reference_build: Biokepi_run_environment.Reference_genome.name ->
[
| `Fastq of [ `Fastq ] repr
| `Fastq_gz of [ `Gz of [ `Fastq ] ] repr
| `Bam of [ `Bam ] repr * [ `PE | `SE ]
] ->
[ `Bam ] repr
```
In branch:
[`covariant-ttfi-repr`](https://github.com/hammerlab/biokepi/tree/covariant-ttfi-repr/)
there is an in-progress version of:
```ocaml
val bwa_mem:
?configuration: Biokepi_bfx_tools.Bwa.Configuration.Mem.t ->
reference_build: Biokepi_run_environment.Reference_genome.name ->
[ `Fastq | `Gz of [ `Fastq ] | `Bam ] repr ->
[ `Bam ] repr
``` …

Bwa with pipes

---

src/environment_setup/tool_providers.ml
src/run_environment/machine.ml

This adds [samblaster](https://github.com/GregoryFaust/samblaster) as an installable tool
Why?
- In `bwa_mem_opt` I can add this to the command:
```
command_to_stdout; "|";
+      "samblaster"; "|";
"samtools"; "view"; "-b"; "|";
```
- it is used for marking duplicates in [bwakit](https://github.com/lh3/bwa/tree/master/bwakit) as well
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hammerlab/biokepi/341)

Add samblaster tool

---

src/environment_setup/netmhc.ml
src/run_environment/workflow_utilities.ml

As @tavinathanson pointed out, the official documentation for the `NetMHCcons` suggest using `NetMHC 3.4` and not the `4.0`. The installation of the former requires special treatment and some more customization to the procedure, so this PR follows up on #344 and adds support for installing `netMHC 3.4`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hammerlab/biokepi/347)

NetMHC: support for installing netmhc 3.4

---

src/pipeline_edsl/to_workflow.ml

Without the module paths, the interaction between packed modules and cmis goes nuts (we've seen that before).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hammerlab/biokepi/352)

Fix module paths in `EDSL.To_workflow`

---

src/environment_setup/conda.ml
src/environment_setup/netmhc.ml

follow-up to #287, #347, and #351 to fix various issues with the latest setup:
- Installs a clean Python 2 environment to be used by NetMHC tools (so that no other Python installation interferes with their function)
- Also fixes the old NetMHC script to force it use whatever Python is available in the `$PATH`
- Improves `Conda`'s init function in such a way that if the environment is already active, it won't get activated once more (provides smooth handling of env variables if one is to init multiple netMHC tools independently)
- Now cleans up after itself on failure
- Creates the `$TMPDIR` beforehand to satisfy `NetMHC`'s weak assumptions
All of these tested on a clean VM on Gcloud, so this should be good to go.
---
This change is [<img src="https://reviewable.io/review_button.svg" …

Better tame the NetMHC tool installations

---

src/environment_setup/conda.ml
src/environment_setup/conda.mli
src/environment_setup/netmhc.ml

so that when another tool (e.g. vaxrank) that depends on another version of Python (e.g. v3) calls one of these scripts, we make sure that we first enter into the environment we set up (Python v2), run the tool and go back to the whatever environment we had :man::gun:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hammerlab/biokepi/355)

NetMHC: wrap the netMHC wrappers for better environment control

---

src/bfx_tools/bedtools.ml
src/bfx_tools/gatk.ml
src/bfx_tools/muse.ml
src/bfx_tools/mutect.ml
src/bfx_tools/somaticsniper.ml
src/bfx_tools/strelka.ml
src/bfx_tools/varscan.ml
src/bfx_tools/vcfannotatepolyphen.ml
src/bfx_tools/vcftools.ml
src/bfx_tools/virmid.ml
src/environment_setup/download_reference_genomes.ml
src/pipeline_edsl/optimization_framework.ml
src/pipeline_edsl/pipeline.ml
src/pipeline_edsl/semantics.ml
src/pipeline_edsl/to_json.ml
src/pipeline_edsl/to_workflow.ml
src/run_environment/common.ml
src/run_environment/workflow_utilities.ml

As we discussed once, there is now a `vcf_file` ketrew-product.
This makes some `reference_build` arguments redundant/useless in the EDSL, so the API-breaking change is that simplification (minor PR to epidisco on the way).
While propagating I fixed a minor bug in `isovar`'s `To_json`/`To_display`.
I also added a couple more "conformity checks" (that VCFs and Bams have the same reference-build).

Implement vcf product

---

src/environment_setup/biopam.ml

To resolve this on systems that already have ncurses installed: https://gist.github.com/armish/c1182de32ac7fd7e6f64eb078cd97cbb

seq2HLA: ban ncurses library from the conda env

---

src/bfx_tools/seq2HLA.ml

This fixes
[`#62`](https://github.com/hammerlab/coclobas/issues/62).

Clean-up work-dir after Seq2HLA failures

---

src/pipeline_edsl/to_workflow.ml

The EDSL was collapsing the names of bedtools intersected products.

Properly name the outputs of Bedtools intersect

---

.travis.yml
src/environment_setup/biopam.ml

These two fixes are needed to get the OptiType working again:
- the version postfix in the folder name generation was breaking how we built the path to the OptiType root
- glpk package that OptiType depends on is not always available with default distributions and even if it is, the relatively new versions do not play nicely with the OptiType. This fixes the version of the glpk package to the one that is compatible with OptiType (more details here: https://github.com/FRED-2/OptiType/issues/28)
Just realized that I completely forgot to push this fix out and make a PR off of it :\

fix OptiType installation and init procedure

---

tools/docker/run/Dockerfile
tools/docker/run/fonts.conf

- adding non-Python dependencies
- adding a font config file needed for good kerning in output PDF (Ubuntu issue)
Tested by creating a local Docker image with this Dockerfile and running vaxrank.

Updating Dockerfile to allow for vaxrank PDF report generation:

---

src/bfx_tools/freebayes.ml
src/environment_setup/tool_providers.ml
src/pipeline_edsl/optimization_framework.ml
src/pipeline_edsl/semantics.ml
src/pipeline_edsl/to_json.ml
src/pipeline_edsl/to_workflow.ml
src/run_environment/machine.ml
tools/docker/run/Dockerfile
tools/docker/run/README.md

fixes https://github.com/hammerlab/biokepi/issues/390
(doesn't add the variant caller,  to the workflow but all the infrastructure is there)

Add FreeBayes bamleftalign

---

src/pipeline_edsl/to_workflow.ml

Tested both commits separately, the first one fixes issues with file-naming, and the second one just avoids useless workflow-nodes that do `cat file.fastq > file-concat.fastq`.

Edsl.concat: fix and improve

---

src/pipeline_edsl/optimization_framework.ml
src/pipeline_edsl/semantics.ml
src/pipeline_edsl/to_json.ml
src/pipeline_edsl/to_workflow.ml

Easily convert BAMs to BAIs in a pipeline.

Add BAM to BAI to the TTFI

---

src/environment_setup/python_package.ml

This new version comes with data structures and filenames for the cached data, so is needed for compatibility across all the pygenomics tools (including vaxrank, isovar, topiary, ...). This and `vaxrank` apparently became out-of-sync after #407 and vaxrank fails when the cache is coming from an older version of pyensembl.

Bump pyensembl version to make it compatible with the latest versions of pygenomics tools

---

src/examples/edsl_extension_register_result.ml
src/pipeline_edsl/pipeline_library.ml
src/pipeline_edsl/pipeline_library.mli

Also rename Input.of_bam to fastq_of_bam
Improve error messages
this fixes an issue in epidisco with the no-realign option @julia326

Add fastq_of_input case for Input.t.Bam

---

src/bfx_tools/topiary.ml
src/environment_setup/python_package.ml
src/pipeline_edsl/optimization_framework.ml
src/pipeline_edsl/semantics.ml
src/pipeline_edsl/to_json.ml
src/pipeline_edsl/to_workflow.ml

Depends on https://github.com/hammerlab/topiary/pull/67.
With this, we will be able to pass multiple VCFs to topiary and this will make it easier to include topiary in the pipeline (cf. https://github.com/hammerlab/epidisco/issues/158)

Bump topiary version and add multiple VCF support

---

src/run_environment/reference_genome.ml

This is needed, for example, when running kallisto against an mm10 sample/reference. Otherwise, any tool asking for the mm10 cDNA breaks the workflow.

Add cDNA for the mm10 genome

---

src/bfx_tools/picard.ml
src/pipeline_edsl/optimization_framework.ml
src/pipeline_edsl/semantics.ml
src/pipeline_edsl/to_json.ml
src/pipeline_edsl/to_workflow.ml

Useful workaround for the following issue with badly constructed BAM files:
```
Exception in thread "main" htsjdk.samtools.SAMFormatException: SAM validation error: ERROR: Read name HWI-D00419_209:1:1102:1640:75904, Read CIGAR M operator maps off end of reference
at htsjdk.samtools.SAMUtils.processValidationErrors(SAMUtils.java:439)
at htsjdk.samtools.BAMRecord.getCigar(BAMRecord.java:247)
at htsjdk.samtools.SAMRecord.getAlignmentEnd(SAMRecord.java:460)
at htsjdk.samtools.SAMRecord.computeIndexingBin(SAMRecord.java:1235)
at htsjdk.samtools.SAMRecord.isValid(SAMRecord.java:1643)
at htsjdk.samtools.BAMFileReader$BAMFileIterator.advance(BAMFileReader.java:642)
at htsjdk.samtools.BAMFileReader$BAMFileIterator.next(BAMFileReader.java:628)
at …
```

Add support for cleaning a BAM via Picard's CleanSam

---

src/environment_setup/build_machine.ml
src/environment_setup/build_machine.mli
src/environment_setup/netmhc.ml
src/environment_setup/tool_providers.ml

Since the one on the mounted folder seems to be causing issues from time to time (reported by @julia326).

Use local tmp dir for NetMHC family

---

src/bfx_tools/vaxrank.ml

to work around this issue: https://github.com/hammerlab/vaxrank/issues/130

Call vaxrank from the `output_folder` instead of the default `root`

---

src/environment_setup/tool_providers.ml

@julia326 found out that mutect v1 has started failing since @smondet's recent migration of biokepi runners from Java 1.7 to 1.8 (c.f. https://github.com/hammerlab/secotrec/issues/64). This is apparently a well-known issue and has been acknowledged by Broad. 
This change wraps the mutect tool with a conda environment that comes with `openjdk-7.x` to make sure it keeps running no matter what the global Java version is.
(Tested and confirmed that this works as intended)

Make MuTect v1 great again

---

src/examples/edsl_extension_register_result.ml
src/pipeline_edsl/semantics.ml
src/pipeline_edsl/to_json.ml
src/pipeline_edsl/to_workflow.ml
src/test/ttfi_pipeline.ml

Still to do:
This has already the advantage of keep around the JSON serialization of the configurations (and not just their name).

Provenance on steroids

---

src/run_environment/reference_genome.ml

Looks like the path to the b37 fasta files has changed.
See ftp://gsapubftp-anonymous@ftp.broadinstitute.org/bundle/b37 to test the current path.

update location to b37 human_g1k_v37.fasta.gz file

---

src/environment_setup/python_package.ml

Correct typo in vaxrank dependency
